=== GrahammerTek/Pawnmorpher/Schemas/ThoughtDef.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Defs">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ThoughtDef" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="defName" type="xs:string" minOccurs="0" maxOccurs="1" />
			  <xs:element name="durationDays" type="xs:float"  minOccurs="0" maxOccurs="1"/>
              <xs:element name="hediff" type="xs:string" minOccurs="0" maxOccurs="1" />
              <xs:element name="stages" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="li" type="ThoughtStage" minOccurs="1" maxOccurs="unbounded" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="ParentName" type="AbstractThoughts" use="optional" />
            <xs:attribute name="Abstract" type="xs:boolean" use="optional" />
            <xs:attribute name="Name" type="xs:string" use="optional" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="AbstractThoughts">
    <xs:restriction base="xs:string">
      <xs:enumeration value="MorphReactionThoughtBase" />
      <xs:enumeration value="MorphReactionThoughtBaseNone" />
      <xs:enumeration value="MorphReactionThoughtBaseFurry" />
      <xs:enumeration value="MorphReactionThoughtBaseBodyPurist" />
      <xs:enumeration value="RevertedThoughtBase" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ThoughtStage">
    <xs:sequence>
      <xs:element name="label" type="xs:string" minOccurs="1" maxOccurs="1" />
      <xs:element name="labelSocial" type="xs:string" minOccurs="0" maxOccurs="1" />
      <xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1" />
      <xs:element name="visible" type="xs:boolean" default="true" minOccurs="0" maxOccurs="1" />
      <xs:element name="baseMoodEffect" type="xs:float" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== GrahammerTek/Pawnmorpher/1.3/Defs/Morphs/Animal/PawFooted/Rodent/Cerebral/Rat/Rat_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/ThoughtDef.xsd">
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>RatTransformationMemory</defName>
        <stages>
            <li>
                <label>Became ratmorph</label>
                <description>I feel like a lab rat... literally!</description>
                <visible>true</visible>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>Became ratmorph</label>
                <description>Eeek!</description>
                <visible>true</visible>
                <baseMoodEffect>3</baseMoodEffect>
            </li>
            <li>
                <label>Became ratmorph</label>
                <description>Am I gonna build a nest in my sleep or something?</description>
                <visible>true</visible>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>

    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>RatRevertedMemory</defName>
		<stages>
            <li>
                <label>reverted</label>
                <description>Back to normal! Those teeth were annoying.</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>Aw, but I kind of liked being a rat.</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>I'm never going to eat cheese again!</description>
                <baseMoodEffect>+10</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>But I wanted to be a cute rat!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>

	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherRatSnout</defName>
		<stages>
			<li>
				<label>Ratty face</label>
				<description>It's too sensitive for my liking. I'm almost overwhelmed with strong smells.</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Ratty face</label>
				<description>A lot of people say rats are gross, but I think this looks good on me!</description>
				<visible>true</visible>
				<baseMoodEffect>2</baseMoodEffect>
			</li>
			<li>
				<label>Ratty face</label>
				<description>I don't want to look like a squeaking PEST!</description>
				<visible>true</visible>
				<baseMoodEffect>-3</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherRatEar</defName>
		<stages>
			<li>
				<label>Rat ears</label>
				<description>They're upright at least.</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Rat ears</label>
				<description>Good for hearing possible enemies!</description>
				<visible>true</visible>
				<baseMoodEffect>1</baseMoodEffect>
			</li>
			<li>
				<label>Rat ears</label>
				<description>I want these cut off.</description>
				<visible>true</visible>
				<baseMoodEffect>-2</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherRatTail</defName>
		<stages>
			<li>
				<label>Rat tail</label>
				<description>It trails behind me uselessly...</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Rat tail</label>
				<description>I wish it was better at something...</description>
				<visible>true</visible>
				<baseMoodEffect>1</baseMoodEffect>
			</li>
			<li>
				<label>Rat tail</label>
				<description>I feel dirty and like a thief, like this is a punishment...</description>
				<visible>true</visible>
				<baseMoodEffect>-2</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherDextrousPawHand</defName>
		<stages>
			<li>
				<label>Rodent hands</label>
				<description>These paws sure are good at picking up little things off the ground.</description>
				<visible>true</visible>
				<baseMoodEffect>1</baseMoodEffect>
			</li>
			<li>
				<label>Rodent hands</label>
				<description>They're so dainty and dextrous, these are better than my old hands!</description>
				<visible>true</visible>
				<baseMoodEffect>3</baseMoodEffect>
			</li>
			<li>
				<label>Rodent hands</label>
				<description>Ahhhhh! They're so wrinkly! Get them off me!</description>
				<visible>true</visible>
				<baseMoodEffect>-3</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherRatFoot</defName>
		<stages>
			<li>
				<label>Rat feet</label>
				<description>Didn't I have five toes?</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Rat feet</label>
				<description>Perfect for stealing and getting out fast!</description>
				<visible>true</visible>
				<baseMoodEffect>2</baseMoodEffect>
			</li>
			<li>
				<label>Rat feet</label>
				<description>I have the feet of a sewer beast!</description>
				<visible>true</visible>
				<baseMoodEffect>-3</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
</Defs>
