=== GrahammerTek/Pawnmorpher/Schemas/ThoughtDef.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Defs">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ThoughtDef" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="defName" type="xs:string" minOccurs="0" maxOccurs="1" />
			  <xs:element name="durationDays" type="xs:float"  minOccurs="0" maxOccurs="1"/>
              <xs:element name="hediff" type="xs:string" minOccurs="0" maxOccurs="1" />
              <xs:element name="stages" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="li" type="ThoughtStage" minOccurs="1" maxOccurs="unbounded" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="ParentName" type="AbstractThoughts" use="optional" />
            <xs:attribute name="Abstract" type="xs:boolean" use="optional" />
            <xs:attribute name="Name" type="xs:string" use="optional" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="AbstractThoughts">
    <xs:restriction base="xs:string">
      <xs:enumeration value="MorphReactionThoughtBase" />
      <xs:enumeration value="MorphReactionThoughtBaseNone" />
      <xs:enumeration value="MorphReactionThoughtBaseFurry" />
      <xs:enumeration value="MorphReactionThoughtBaseBodyPurist" />
      <xs:enumeration value="RevertedThoughtBase" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ThoughtStage">
    <xs:sequence>
      <xs:element name="label" type="xs:string" minOccurs="1" maxOccurs="1" />
      <xs:element name="labelSocial" type="xs:string" minOccurs="0" maxOccurs="1" />
      <xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1" />
      <xs:element name="visible" type="xs:boolean" default="true" minOccurs="0" maxOccurs="1" />
      <xs:element name="baseMoodEffect" type="xs:float" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== GrahammerTek/Pawnmorpher/1.3/Defs/Morphs/Chicken/Chicken_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/ThoughtDef.xsd">
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>ChickenTransformationMemory</defName>
        <stages>
            <li>
                <label>morphed</label>
                <description>I'm... covered in feathers... OUCH! What!? Did I just lay an *egg*! Oh no...</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
              <label>morphed</label>
                <description>I'm all feathery, and these wings are nea- BWAK! What the- An egg! Neat!</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
              <label>morphed</label>
                <description>Oh man, these feathers are disgusting, and the talons look fr- BWAK! What the â€” oh no... please tell me that's not an egg...</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
              <label>morphed</label>
                <description>These feathers and talons are so good, and laying eggs! If only I could just settle down in a nesting box.</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>

    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>ChickenRevertedMemory</defName>
        <stages>
            <li>
                <label>reverted</label>
                <description>I'm back to my normal, human self again! No more laying eggs. Or eating eggs, please.</description>
                <baseMoodEffect>3</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>But the feathers! The *eggs*! Didn't you like the breakfast I made?</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>Hands and feet. And most important, no more eggs. EVER.</description>
                <baseMoodEffect>10</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>I'm human again? I think I wanted the opposite of this.</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>

	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherTailfeathers</defName>
		<stages>
			<li>
				<label>Tailfeathers</label>
				<description>...does this make my butt look big?</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Tailfeathers</label>
				<description>It's kind of fun to wiggle it.</description>
				<visible>true</visible>
				<baseMoodEffect>1</baseMoodEffect>
			</li>
			<li>
				<label>Tailfeathers</label>
				<description>I look like a damn chicken, whyyyy?!</description>
				<visible>true</visible>
				<baseMoodEffect>-2</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherEggLayer</defName>
		<stages>
			<li>
				<label>...eggs?!</label>
				<description>How is this even possible? It feels so weird...</description>
				<visible>true</visible>
				<baseMoodEffect>-5</baseMoodEffect>
			</li>
			<li>
				<label>...eggs?!</label>
				<description>This is taking it too far. People weren't meant to lay eggs!</description>
				<visible>true</visible>
				<baseMoodEffect>-3</baseMoodEffect>
			</li>
			<li>
				<label>...eggs?!</label>
				<description>How!? Why!? What has become of me!?</description>
				<visible>true</visible>
				<baseMoodEffect>-10</baseMoodEffect>
			</li>
			<li>
				<label>...eggs?!</label>
				<description>I know I wanted this, but I'm not entirely sure now.</description>
				<visible>true</visible>
				<baseMoodEffect>0</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherBeak</defName>
		<stages>
			<li>
				<label>Beak</label>
				<description>I can't talk properly with this stupid beak!</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Beak</label>
				<description>Time to peck everyone I don't like.</description>
				<visible>true</visible>
				<baseMoodEffect>2</baseMoodEffect>
			</li>
			<li>
				<label>Beak</label>
				<description>My face! This is awf-bawk!</description>
				<visible>true</visible>
				<baseMoodEffect>-3</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
</Defs>

=== GrahammerTek/Pawnmorpher/1.3/Defs/Morphs/Monkey/Monkey_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/ThoughtDef.xsd">
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>MonkeyTransformationMemory</defName>
        <stages>
            <li>
                <label>changed</label>
                <description>I don't look *that* different, right?</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>changed</label>
                <description>Oooh oooh ah ah! I feel closer to my roots.</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>changed</label>
                <description>It feels like I've gone back three steps in the evolutionary tree!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>changed</label>
                <description>Monkey see, monkey do?</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>

    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>MonkeyRevertedMemory</defName>
        <stages>
            <li>
                <label>reverted</label>
                <description>I need to shave, I think I'm still hairier than before.</description>
                <baseMoodEffect>3</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>I suppose all things must come to an end...</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>HUMAN AGAIN!</description>
                <baseMoodEffect>10</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>This isn't what I wanted.</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>

	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherMonkeyJaw</defName>
		<stages>
			<li>
				<label>Monkey face</label>
				<description>I feel like I need to shave constantly...</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Monkey face</label>
				<description>This isn't really all that different...</description>
				<visible>true</visible>
				<baseMoodEffect>2</baseMoodEffect>
			</li>
			<li>
				<label>Monkey face</label>
				<description>I've taken a step *back*! This is terrible!</description>
				<visible>true</visible>
				<baseMoodEffect>-3</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherMonkeyEar</defName>
		<stages>
			<li>
				<label>Monkey ears</label>
				<description>My ears...they feel like they're larger.</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Monkey ears</label>
				<description>Bigger ears! Awesome!</description>
				<visible>true</visible>
				<baseMoodEffect>1</baseMoodEffect>
			</li>
			<li>
				<label>Monkey ears</label>
				<description>Why are my ears bigger, that's almost useless!</description>
				<visible>true</visible>
				<baseMoodEffect>-2</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherMonkeyTail</defName>
		<stages>
			<li>
				<label>Monkey tail</label>
				<description>Huh...I can pick things up with this tail. Neat.</description>
				<visible>true</visible>
				<baseMoodEffect>0</baseMoodEffect>
			</li>
			<li>
				<label>Monkey tail</label>
				<description>It's like another hand. Who needs bionics when you have this?</description>
				<visible>true</visible>
				<baseMoodEffect>2</baseMoodEffect>
			</li>
			<li>
				<label>Monkey tail</label>
				<description>I can feel it moving, and I really don't like the sensation of being able to control it!</description>
				<visible>true</visible>
				<baseMoodEffect>-2</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherMonkeyHand</defName>
		<stages>
			<li>
				<label>Hairy hands</label>
				<description>These kinda look like my normal hands...just more primitive.</description>
				<visible>true</visible>
				<baseMoodEffect>0</baseMoodEffect>
			</li>
			<li>
				<label>Hairy hands</label>
				<description>I might get good wishes out these monkey paws!</description>
				<visible>true</visible>
				<baseMoodEffect>2</baseMoodEffect>
			</li>
			<li>
				<label>Hairy hands</label>
				<description>My hands! They look weird and old!</description>
				<visible>true</visible>
				<baseMoodEffect>-2</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherMonkeyFoot</defName>
		<stages>
			<li>
				<label>Hairy feet</label>
				<description>Why can I grab things with my feet?</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Hairy feet</label>
				<description>Even more hands!</description>
				<visible>true</visible>
				<baseMoodEffect>2</baseMoodEffect>
			</li>
			<li>
				<label>Hairy feet</label>
				<description>Why do my shoes feel so big, and my feet so small?</description>
				<visible>true</visible>
				<baseMoodEffect>-3</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
</Defs>

=== GrahammerTek/Pawnmorpher/Defs/Morphs/Monkey/Monkey_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/ThoughtDef.xsd">
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>MonkeyTransformationMemory</defName>
        <stages>
            <li>
                <label>!!!MonkeyTransformationMemory's default stage needs a label!!!</label>
                <description>!!!MonkeyTransformationMemory's default stage needs a description!!!</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>!!!MonkeyTransformationMemory's mutation affinity stage needs a label!!!</label>
                <description>!!!MonkeyTransformationMemory's mutation affinity stage needs a description!!!</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>!!!MonkeyTransformationMemory's body purist stage needs a label!!!</label>
                <description>!!!MonkeyTransformationMemory's body purist stage needs a description!!!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>!!!MonkeyTransformationMemory's primal wish stage needs a label!!!</label>
                <description>!!!MonkeyTransformationMemory's primal wish stage needs a description!!!</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
	
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>MonkeyRevertedMemory</defName>
        <stages>
            <li>
                <label>!!!MonkeyRevertedMemory's default stage needs a label!!!</label>
                <description>!!!MonkeyRevertedMemory's default stage needs a description!!!</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>!!!MonkeyRevertedMemory's mutation affinity stage needs a label!!!</label>
                <description>!!!MonkeyRevertedMemory's mutation affinity stage needs a description!!!</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>!!!MonkeyRevertedMemory's body purist stage needs a label!!!</label>
                <description>!!!MonkeyRevertedMemory's body purist stage needs a description!!!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>!!!MonkeyRevertedMemory's primal wish stage needs a label!!!</label>
                <description>!!!MonkeyRevertedMemory's primal wish stage needs a description!!!</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
</Defs>

=== GrahammerTek/Pawnmorpher/Defs/Morphs/Pig/Pig_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/ThoughtDef.xsd">
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>PigTransformationMemory</defName>
        <stages>
            <li>
                <label>!!!PigTransformationMemory's default stage needs a label!!!</label>
                <description>!!!PigTransformationMemory's default stage needs a description!!!</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>!!!PigTransformationMemory's mutation affinity stage needs a label!!!</label>
                <description>!!!PigTransformationMemory's mutation affinity stage needs a description!!!</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>!!!PigTransformationMemory's body purist stage needs a label!!!</label>
                <description>!!!PigTransformationMemory's body purist stage needs a description!!!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>!!!PigTransformationMemory's primal wish stage needs a label!!!</label>
                <description>!!!PigTransformationMemory's primal wish stage needs a description!!!</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
	
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>PigRevertedMemory</defName>
        <stages>
            <li>
                <label>!!!PigRevertedMemory's default stage needs a label!!!</label>
                <description>!!!PigRevertedMemory's default stage needs a description!!!</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>!!!PigRevertedMemory's mutation affinity stage needs a label!!!</label>
                <description>!!!PigRevertedMemory's mutation affinity stage needs a description!!!</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>!!!PigRevertedMemory's body purist stage needs a label!!!</label>
                <description>!!!PigRevertedMemory's body purist stage needs a description!!!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>!!!PigRevertedMemory's primal wish stage needs a label!!!</label>
                <description>!!!PigRevertedMemory's primal wish stage needs a description!!!</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
</Defs>

=== GrahammerTek/Pawnmorpher/Defs/Morphs/Boomrat/Boomrat_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/ThoughtDef.xsd">
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>BoomratTransformationMemory</defName>
        <stages>
            <li>
                <label>!!!BoomratTransformationMemory's default stage needs a label!!!</label>
                <description>!!!BoomratTransformationMemory's default stage needs a description!!!</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>!!!BoomratTransformationMemory's mutation affinity stage needs a label!!!</label>
                <description>!!!BoomratTransformationMemory's mutation affinity stage needs a description!!!</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>!!!BoomratTransformationMemory's body purist stage needs a label!!!</label>
                <description>!!!BoomratTransformationMemory's body purist stage needs a description!!!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>!!!BoomratTransformationMemory's primal wish stage needs a label!!!</label>
                <description>!!!BoomratTransformationMemory's primal wish stage needs a description!!!</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
	
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>BoomratRevertedMemory</defName>
        <stages>
            <li>
                <label>!!!BoomratRevertedMemory's default stage needs a label!!!</label>
                <description>!!!BoomratRevertedMemory's default stage needs a description!!!</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>!!!BoomratRevertedMemory's mutation affinity stage needs a label!!!</label>
                <description>!!!BoomratRevertedMemory's mutation affinity stage needs a description!!!</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>!!!BoomratRevertedMemory's body purist stage needs a label!!!</label>
                <description>!!!BoomratRevertedMemory's body purist stage needs a description!!!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>!!!BoomratRevertedMemory's primal wish stage needs a label!!!</label>
                <description>!!!BoomratRevertedMemory's primal wish stage needs a description!!!</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
</Defs>

=== GrahammerTek/Pawnmorpher/Defs/Thoughts/SapientAnimalThoughts/FH_Pals.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/ThoughtDef.xsd">
    
    <!--this thought is for when a former human is bonded to one or more regular animals  -->
    <ThoughtDef>
        <defName>FormerHumanPalsThought</defName>
        <workerClass>Pawnmorph.Thoughts.AnimalPalsWorker</workerClass>
        <stages>
            <li>
                <label>Sapient</label>
                <description>TODO</description>
            </li>
            <li>
                <label>MostlySapient</label>
                <description>TODO</description>
            </li>
            <li>
                <label>Conflicted</label>
                <description>TODO</description>
            </li>
            <li>
                <label>MostlyFeral</label>
                <description>TODO</description>
            </li>
        </stages>
    </ThoughtDef>

    <!-- this thought is for when a former human is bonded to one or more former humans  -->
    <ThoughtDef>
        <defName>FormerHumanPalsThought</defName>
        <workerClass>Pawnmorph.Thoughts.FormerHumanPalsWorker</workerClass>
        <stages>
            <li>
                <label>Sapient</label>
                <description>TODO</description>
            </li>
            <li>
                <label>MostlySapient</label>
                <description>TODO</description>
            </li>
            <li>
                <label>Conflicted</label>
                <description>TODO</description>
            </li>
            <li>
                <label>MostlyFeral</label>
                <description>TODO</description>
            </li>
        </stages>
    </ThoughtDef>

</Defs>

=== GrahammerTek/Pawnmorpher/Defs/Morphs/Squirrel/Squirrel_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/ThoughtDef.xsd">
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>SquirrelTransformationMemory</defName>
        <stages>
            <li>
                <label>!!!SquirrelTransformationMemory's default stage needs a label!!!</label>
                <description>!!!SquirrelTransformationMemory's default stage needs a description!!!</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>!!!SquirrelTransformationMemory's mutation affinity stage needs a label!!!</label>
                <description>!!!SquirrelTransformationMemory's mutation affinity stage needs a description!!!</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>!!!SquirrelTransformationMemory's body purist stage needs a label!!!</label>
                <description>!!!SquirrelTransformationMemory's body purist stage needs a description!!!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>!!!SquirrelTransformationMemory's primal wish stage needs a label!!!</label>
                <description>!!!SquirrelTransformationMemory's primal wish stage needs a description!!!</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
	
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>SquirrelRevertedMemory</defName>
        <stages>
            <li>
                <label>!!!SquirrelRevertedMemory's default stage needs a label!!!</label>
                <description>!!!SquirrelRevertedMemory's default stage needs a description!!!</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>!!!SquirrelRevertedMemory's mutation affinity stage needs a label!!!</label>
                <description>!!!SquirrelRevertedMemory's mutation affinity stage needs a description!!!</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>!!!SquirrelRevertedMemory's body purist stage needs a label!!!</label>
                <description>!!!SquirrelRevertedMemory's body purist stage needs a description!!!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>!!!SquirrelRevertedMemory's primal wish stage needs a label!!!</label>
                <description>!!!SquirrelRevertedMemory's primal wish stage needs a description!!!</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
</Defs>

=== GrahammerTek/Pawnmorpher/Defs/Morphs/Cobra/Cobra_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/ThoughtDef.xsd">
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>CobraTransformationMemory</defName>
        <stages>
            <li>
                <label>!!!CobraTransformationMemory's default stage needs a label!!!</label>
                <description>!!!CobraTransformationMemory's default stage needs a description!!!</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>!!!CobraTransformationMemory's mutation affinity stage needs a label!!!</label>
                <description>!!!CobraTransformationMemory's mutation affinity stage needs a description!!!</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>!!!CobraTransformationMemory's body purist stage needs a label!!!</label>
                <description>!!!CobraTransformationMemory's body purist stage needs a description!!!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>!!!CobraTransformationMemory's primal wish stage needs a label!!!</label>
                <description>!!!CobraTransformationMemory's primal wish stage needs a description!!!</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
	
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>CobraRevertedMemory</defName>
        <stages>
            <li>
                <label>!!!CobraRevertedMemory's default stage needs a label!!!</label>
                <description>!!!CobraRevertedMemory's default stage needs a description!!!</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>!!!CobraRevertedMemory's mutation affinity stage needs a label!!!</label>
                <description>!!!CobraRevertedMemory's mutation affinity stage needs a description!!!</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>!!!CobraRevertedMemory's body purist stage needs a label!!!</label>
                <description>!!!CobraRevertedMemory's body purist stage needs a description!!!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>!!!CobraRevertedMemory's primal wish stage needs a label!!!</label>
                <description>!!!CobraRevertedMemory's primal wish stage needs a description!!!</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
</Defs>
