=== GrahammerTek/Pawnmorpher/Schemas/ThoughtDef.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Defs">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ThoughtDef" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="defName" type="xs:string" minOccurs="0" maxOccurs="1" />
			  <xs:element name="durationDays" type="xs:float"  minOccurs="0" maxOccurs="1"/>
              <xs:element name="hediff" type="xs:string" minOccurs="0" maxOccurs="1" />
              <xs:element name="stages" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="li" type="ThoughtStage" minOccurs="1" maxOccurs="unbounded" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="ParentName" type="AbstractThoughts" use="optional" />
            <xs:attribute name="Abstract" type="xs:boolean" use="optional" />
            <xs:attribute name="Name" type="xs:string" use="optional" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="AbstractThoughts">
    <xs:restriction base="xs:string">
      <xs:enumeration value="MorphReactionThoughtBase" />
      <xs:enumeration value="MorphReactionThoughtBaseNone" />
      <xs:enumeration value="MorphReactionThoughtBaseFurry" />
      <xs:enumeration value="MorphReactionThoughtBaseBodyPurist" />
      <xs:enumeration value="RevertedThoughtBase" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="ThoughtStage">
    <xs:sequence>
      <xs:element name="label" type="xs:string" minOccurs="1" maxOccurs="1" />
      <xs:element name="labelSocial" type="xs:string" minOccurs="0" maxOccurs="1" />
      <xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1" />
      <xs:element name="visible" type="xs:boolean" default="true" minOccurs="0" maxOccurs="1" />
      <xs:element name="baseMoodEffect" type="xs:float" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== GrahammerTek/Pawnmorpher/1.3/Defs/Morphs/Fox/Arctic Fox/ArcticFox_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/ThoughtDef.xsd">

	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherArcticFoxMuzzle</defName>
		<stages>
			<li>
				<label>Fox face</label>
				<description>I just licked my nose...eww.</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Fox face</label>
				<description>Oh, so that's how foxes make all those cool noises! Yip!</description>
				<visible>true</visible>
				<baseMoodEffect>2</baseMoodEffect>
			</li>
			<li>
				<label>Fox face</label>
				<description>My face is ruined, and I can't even talk right!</description>
				<visible>true</visible>
				<baseMoodEffect>-3</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherArcticFoxEar</defName>
		<stages>
			<li>
				<label>Fox ears</label>
				<description>Okay, I'll admit it, these are pretty cool.</description>
				<visible>true</visible>
				<baseMoodEffect>1</baseMoodEffect>
			</li>
			<li>
				<label>Fox ears</label>
				<description>Pointy and fluffy ears, these are great â€” and I can hear everything!</description>
				<visible>true</visible>
				<baseMoodEffect>2</baseMoodEffect>
			</li>
			<li>
				<label>Fox ears</label>
				<description>...if there's one awful mutation I'm OK with...</description>
				<visible>true</visible>
				<baseMoodEffect>0</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherArcticFluffyTail</defName>
		<stages>
			<li>
				<label>Fluffy tail</label>
				<description>It gets in the way, but it's really fluffy...I could almost use it as a pillow.</description>
				<visible>true</visible>
				<baseMoodEffect>1</baseMoodEffect>
			</li>
			<li>
				<label>Fluffy tail</label>
				<description>It's so fluffy I think I'm gonna die!</description>
				<visible>true</visible>
				<baseMoodEffect>2</baseMoodEffect>
			</li>
			<li>
				<label>Fluffy tail</label>
				<description>Sure it's cute...but it's attached to me!</description>
				<visible>true</visible>
				<baseMoodEffect>-2</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
</Defs>

=== GrahammerTek/Pawnmorpher/Defs/Morphs/Alpaca/Alpaca_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/ThoughtDef.xsd">
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>AlpacaTransformationMemory</defName>
        <stages>
            <li>
                <label>!!!AlpacaTransformationMemory's default stage needs a label!!!</label>
                <description>!!!AlpacaTransformationMemory's default stage needs a description!!!</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>!!!AlpacaTransformationMemory's mutation affinity stage needs a label!!!</label>
                <description>!!!AlpacaTransformationMemory's mutation affinity stage needs a description!!!</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>!!!AlpacaTransformationMemory's body purist stage needs a label!!!</label>
                <description>!!!AlpacaTransformationMemory's body purist stage needs a description!!!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>!!!AlpacaTransformationMemory's primal wish stage needs a label!!!</label>
                <description>!!!AlpacaTransformationMemory's primal wish stage needs a description!!!</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
	
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>AlpacaRevertedMemory</defName>
        <stages>
            <li>
                <label>!!!AlpacaRevertedMemory's default stage needs a label!!!</label>
                <description>!!!AlpacaRevertedMemory's default stage needs a description!!!</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>!!!AlpacaRevertedMemory's mutation affinity stage needs a label!!!</label>
                <description>!!!AlpacaRevertedMemory's mutation affinity stage needs a description!!!</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>!!!AlpacaRevertedMemory's body purist stage needs a label!!!</label>
                <description>!!!AlpacaRevertedMemory's body purist stage needs a description!!!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>!!!AlpacaRevertedMemory's primal wish stage needs a label!!!</label>
                <description>!!!AlpacaRevertedMemory's primal wish stage needs a description!!!</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
</Defs>

=== GrahammerTek/Pawnmorpher/1.3/Defs/Morphs/Caribou/Caribou_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/ThoughtDef.xsd">
    <ThoughtDef ParentName="OutlookMemoryBase">
        <defName>CaribouTransformationMemory</defName>
        <stages>
            <li>
                <label>TODO</label>
                <description>TODO</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>TODO</label>
                <description>TODO</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>TODO</label>
                <description>TODO</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>TODO</label>
                <description>TODO</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>

    <ThoughtDef ParentName="OutlookMemoryBase">
        <defName>CaribouRevertedMemory</defName>
        <stages>
            <li>
                <label>TODO</label>
                <description>TODO</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>TODO</label>
                <description>TODO</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>TODO</label>
                <description>TODO</description>
                <baseMoodEffect>+10</baseMoodEffect>
            </li>
            <li>
                <label>TODO</label>
                <description>TODO</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>

    <ThoughtDef ParentName="OutlookMemoryBase">
        <durationDays>1</durationDays>
        <defName>EtherCaribouEar</defName>
        <stages>
            <li>
                <label>Reindeer ears</label>
                <description>At least they keep the flies off themselves...?</description>
                <visible>True</visible>
                <baseMoodEffect>-1</baseMoodEffect>
            </li>
            <li>
                <label>Reindeer ears</label>
                <description>I can hear everything!</description>
                <visible>True</visible>
                <baseMoodEffect>1</baseMoodEffect>
            </li>
            <li>
                <label>Reindeer ears</label>
                <description>These things are so twitchy, get them off me!</description>
                <visible>True</visible>
                <baseMoodEffect>-2</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>


    <ThoughtDef ParentName="OutlookMemoryBase">
        <durationDays>1</durationDays>
        <defName>EtherCaribouTail</defName>
        <stages>
            <li>
                <label>Short tail</label>
                <description>Is this thing... a tail?</description>
                <visible>True</visible>
                <baseMoodEffect>-1</baseMoodEffect>
            </li>
            <li>
                <label>Short tail</label>
                <description>It's so fluffy!</description>
                <visible>True</visible>
                <baseMoodEffect>1</baseMoodEffect>
            </li>
            <li>
                <label>Short tail</label>
                <description>Just big enough to be hard to hide... great...</description>
                <visible>True</visible>
                <baseMoodEffect>-2</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
</Defs>

=== GrahammerTek/Pawnmorpher/1.3/Defs/Morphs/Panther/Panther_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/ThoughtDef.xsd">
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>PantherTransformationMemory</defName>
        <stages>
            <li>
                <label>changed</label>
                <description>I have this uncontrollable urge to pounce and hunt things.</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>changed</label>
                <description>I'm so sleek and svelte, this is fantastic!</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>changed</label>
                <description>I don't want to be a stupid big cat! I hate cats!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>changed</label>
                <description>Meow! Now, to go the rest of the way?</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>

    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>PantherRevertedMemory</defName>
        <stages>
            <li>
                <label>reverted</label>
                <description>Those claws were really getting in the way.</description>
                <baseMoodEffect>3</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>Not fair, I enjoyed feeling so sleek.</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>Finally, no more hairballs!</description>
                <baseMoodEffect>10</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>This is the opposite of what I wanted.</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>

	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherPantherJaw</defName>
		<stages>
			<li>
				<label>Panther face</label>
				<description>It's hard to talk without purring.</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Panther face</label>
				<description>Mrrow!</description>
				<visible>true</visible>
				<baseMoodEffect>2</baseMoodEffect>
			</li>
			<li>
				<label>Panther face</label>
				<description>No! I don't want to purr!</description>
				<visible>true</visible>
				<baseMoodEffect>-3</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherPantherEar</defName>
		<stages>
			<li>
				<label>Panther ears</label>
				<description>As far as things go, these aren't too bad.</description>
				<visible>true</visible>
				<baseMoodEffect>1</baseMoodEffect>
			</li>
			<li>
				<label>Panther ears</label>
				<description>I can hear everything!</description>
				<visible>true</visible>
				<baseMoodEffect>2</baseMoodEffect>
			</li>
			<li>
				<label>Panther ears</label>
				<description>I feel like an anime character...</description>
				<visible>true</visible>
				<baseMoodEffect>-2</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherPantherTail</defName>
		<stages>
			<li>
				<label>Panther tail</label>
				<description>Why does this thing move so much?</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Panther tail</label>
				<description>It's so smooth and sleek!</description>
				<visible>true</visible>
				<baseMoodEffect>1</baseMoodEffect>
			</li>
			<li>
				<label>Panther tail</label>
				<description>How am I supposed to sit down in a chair with this thing?</description>
				<visible>true</visible>
				<baseMoodEffect>-2</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
</Defs>

=== GrahammerTek/Pawnmorpher/Defs/Morphs/Hare/HareBase_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/ThoughtDef.xsd">
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>HareTransformationMemory</defName>
        <stages>
            <li>
                <label>!!!HareTransformationMemory's default stage needs a label!!!</label>
                <description>!!!HareTransformationMemory's default stage needs a description!!!</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>!!!HareTransformationMemory's mutation affinity stage needs a label!!!</label>
                <description>!!!HareTransformationMemory's mutation affinity stage needs a description!!!</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>!!!HareTransformationMemory's body purist stage needs a label!!!</label>
                <description>!!!HareTransformationMemory's body purist stage needs a description!!!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>!!!HareTransformationMemory's primal wish stage needs a label!!!</label>
                <description>!!!HareTransformationMemory's primal wish stage needs a description!!!</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
	
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>HareRevertedMemory</defName>
        <stages>
            <li>
                <label>!!!HareRevertedMemory's default stage needs a label!!!</label>
                <description>!!!HareRevertedMemory's default stage needs a description!!!</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>!!!HareRevertedMemory's mutation affinity stage needs a label!!!</label>
                <description>!!!HareRevertedMemory's mutation affinity stage needs a description!!!</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>!!!HareRevertedMemory's body purist stage needs a label!!!</label>
                <description>!!!HareRevertedMemory's body purist stage needs a description!!!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>!!!HareRevertedMemory's primal wish stage needs a label!!!</label>
                <description>!!!HareRevertedMemory's primal wish stage needs a description!!!</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
</Defs>

=== GrahammerTek/Pawnmorpher/1.3/Defs/Morphs/Animal/PawFooted/Carnivora/Canid/Familiaris/LabradorRetriever/LabradorRetriever_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/ThoughtDef.xsd">
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>LabradorRetrieverTransformationMemory</defName>
        <stages>
            <li>
                <label>changed</label>
                <description>So I'm the pet dog now? ...arf?</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>changed</label>
                <description>Did somebody say 'belly rub'?</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>changed</label>
                <description>They keep telling me 'fetch'...but I'm not a damn dog!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>changed</label>
                <description>Fetch?! Where!?</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
	
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>LabradorRetrieverRevertedMemory</defName>
        <stages>
            <li>
                <label>reverted</label>
                <description>Too much panting for me.</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>Now I'm sad, I liked barking at people!</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>Thank goodness...I don't think I could cope with that much happiness.</description>
                <baseMoodEffect>+10</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>I think I wanted the opposite of this.</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>

	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherLabradorRetrieverJaw</defName>
		<stages>
			<li>
				<label>Dog face</label>
				<description>I just need to pant all the time...</description>
				<visible>true</visible>
				<baseMoodEffect>1</baseMoodEffect>
			</li>
			<li>
				<label>Dog face</label>
				<description>Look at my happy smile!</description>
				<visible>true</visible>
				<baseMoodEffect>3</baseMoodEffect>
			</li>
			<li>
				<label>Dog face</label>
				<description>I can't be sad with this smile...</description>
				<visible>true</visible>
				<baseMoodEffect>0</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherLabradorRetrieverEar</defName>
		<stages>
			<li>
				<label>Dog ears</label>
				<description>They flop around all the time, it's distracting.</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Dog ears</label>
				<description>I can hear better, and they're floppy and cute!</description>
				<visible>true</visible>
				<baseMoodEffect>1</baseMoodEffect>
			</li>
			<li>
				<label>Dog ears</label>
				<description>I want my own ears back, give them BARK!</description>
				<visible>true</visible>
				<baseMoodEffect>-2</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherLabradorRetrieverTail</defName>
		<stages>
			<li>
				<label>Dog tail</label>
				<description>Now everyone knows what I'm thinking!</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Dog tail</label>
				<description>Awwww, it's so cute on me!</description>
				<visible>true</visible>
				<baseMoodEffect>1</baseMoodEffect>
			</li>
			<li>
				<label>Dog tail</label>
				<description>Why do I have to ruin all my pants for a tail that won't stop wagging?</description>
				<visible>true</visible>
				<baseMoodEffect>-2</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
</Defs>

=== GrahammerTek/Pawnmorpher/1.3/Defs/Morphs/Capybara/Capybara_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../Schemas/ThoughtDef.xsd">
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>CapybaraTransformationMemory</defName>
        <stages>
            <li>
                <label>morphed</label>
                <description>I'm a.. Rodent of some kind? These teeth are awkward.</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>morphed</label>
                <description>I have a lovely coat of fur, even if it is a tad thin.</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>morphed</label>
                <description>This is awful! Look at my teeth, what happened to my legs?! Help!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>morphed</label>
                <description>One step closer to the wild side.</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
	
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>CapybaraRevertedMemory</defName>
        <stages>
            <li>
                <label>reverted</label>
                <description>Back to normal, that fur was getting a bit itchy.</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>I miss my fur, it was nice and warm.</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>Aah, back to normal. I've never missed my skin so much.</description>
                <baseMoodEffect>+10</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>No! I was so close! Why did they change me back?!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>

    <ThoughtDef ParentName="OutlookMemoryBase">
        <durationDays>1</durationDays>
        <defName>EtherCapybaraJaw</defName>
        <stages>
            <li>
                <label>Rodent face</label>
                <description>What's up with these teeth?</description>
                <visible>True</visible>
                <baseMoodEffect>0</baseMoodEffect>
            </li>
            <li>
                <label>Rodent face</label>
                <description>I can eat whatever I want!</description>
                <visible>True</visible>
                <baseMoodEffect>2</baseMoodEffect>
            </li>
            <li>
                <label>Rodent face</label>
                <description>God, I look so ugly with this thing...</description>
                <visible>True</visible>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
    <ThoughtDef ParentName="OutlookMemoryBase">
        <durationDays>1</durationDays>
        <defName>EtherCapybaraEar</defName>
        <stages>
            <li>
                <label>Rodent ears</label>
                <description>Why are my ears so small?</description>
                <visible>True</visible>
                <baseMoodEffect>0</baseMoodEffect>
            </li>
            <li>
                <label>Rodent ears</label>
                <description>These tiny ears are so cute!</description>
                <visible>True</visible>
                <baseMoodEffect>2</baseMoodEffect>
            </li>
            <li>
                <label>Rodent ears</label>
                <description>Does anyone have a hat I can hide these things under?</description>
                <visible>True</visible>
                <baseMoodEffect>-2</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
    
</Defs>
